name: Test Reviewer Add

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  test-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Add Reviewer
        uses: peter-evans/reviewers@v1
        with:
          reviewers: srisarma0402
