name: Test Reviewer Add

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  test-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Add Reviewer
        uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with:
          reviewers: srisarma04024
          token: ${{ secrets.GITHUB_TOKEN }}
